### ISSUE TITLE
are both packages needed for the end user?

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt6pas#36]
I as dev, need both packages (libqt6pas6 and ....dev).
But does end user need both of them?
what if I specify only libqt6pas6 in the 'control' file for DEB, is it enough?

my 'control' file has line:
```

Depends: qt6-base-dev, libqt6pas6, libqt6pas6-dev, python3 (>= 3.8)

```

**Comment by davidbannon** [comment]
Yes, most certainly. As a general rule, you should not install -dev packages on an end user's machine.

The exceptions I know about (that only apply of course if you need the main package) -
* openssl - because FPC322 is so old, it will not work with today's system unless you also install the dev package.
* libfontconfig-dev - because of a bug in FPC (which they have declined to fix) you must install the -dev package or an app using libfontconfig will not find it.

Davo
